### PR TITLE
Add dserve URLs to wp-calypso

### PR DESCRIPTION
**Pull request by alisterscott**
This adds a comment to wp-calypso PRs (a8c contributors only) with a dserve link

### CODE REVIEW

**Comment by sirreal** [comment]
I just received a ping from a closed issue that seems to be related:

https://github.com/Automattic/wp-calypso/issues/3#issuecomment-359375769

Is this live? Any idea where that ping would be from? I wouldn't expect bots to touch issues like that.

**Comment by lsinger** [comment]
Also got the same ping (I think because I used `#3` in a commit message once). But it's unclear why the bot commented on the issue.

**Comment by brbrr** [comment]
@sirreal @lsinger Sorry folks, that's was me. I've tested this PR, and forget to switch to test repo, that's why all the comments were posted into the wp-calypso repo. My apologies. (I'll delete that comment from `#3`)

**Comment by brbrr** [comment]
Changes works as expected, good job 👍 

:shipit:

**Comment by alisterscott** [comment]
Merghing this now with dserve links, and I will do a quick PR to merge when we switch to using calypso.live for dserve :)

**Comment by alisterscott** [comment]
Reverted in #22 - Calyso.live links added by Matticbot which will work when DServe resides at Calypso.live

**Comment by samouri** [comment]
Why did we revert this?
I don't have any timeline for when the switch will happen :(

**Comment by hoverduck** [comment]
One of the reasons it was implemented was because the MC GitHub hook wasn't working to post calypso.live links, but that's been fixed

**Comment by alisterscott** [comment]
@samouri the issue was that matticbot from MC was adding calypso.live and this was adding dserve.a8c.com and matticbot thought dserve.a8c.com was also a private link so we'd get a slack ping each time this was added. So it makes sense to just use calypso.live and update the DNS - fingers crossed this happens soon 🤞

**Pull request merged**
