### PR TITLE
Add IE11 Canary support for calypso

### PR DESCRIPTION
**Pull request by alisterscott**
Adding the regular needs review label also executes IE11 canary test and reports back separate status

This PR includes lots of clean up including running eslint automatically in CircleCI

### CODE REVIEW

**Comment by alisterscott** [comment]
@brbrr @bsessions85 would you mind having a look at this? I think you're the only ones familiar with this code - it should be _slightly_ cleaner than last time - but still needs some longer term clean up on this

**Comment by samouri** [comment]
Total drive by:  I noticed there are a lot of whitespace changes in this pr. Have y'all considered using `prettier` to save time?

---
@alisterscott: let me know if theres any way I can help push this forward. I'd also be happy to test if you pointed me towards some testing instructions

**Comment by brbrr** [comment]
The tests were nicely launched:
```
Executing CALYPSO e2e canary tests for branch: 'add/ie11-canary-support'
Executing CALYPSO e2e canary IE11 tests for branch: 'add/ie11-canary-support'
Tests have been kicked off - updating PR status now
Tests have been kicked off - updating PR status now
GitHub status updated
GitHub status updated
```
But both builds get stuck on waiting for the live branch to be ready. I assume it's because it tries to launch not existed branch (`add/ie11-canary-support`)

So it should be good to go! :shipit: 


@samouri you can check this repo's README as a starting point.

**Comment by alisterscott** [comment]
@brbrr thanks for your review 👍 
@samouri I'll look at adding prettier - this change has a lot of whitespace as I ran linting and converted white space to tabs

**Pull request merged**
